scoring:
    email_expuesto: 8
    telefono_expuesto: 10
    datos_personales_expuestos: 15
    riesgo_doxing_agrupado: 25
    datos_recientes: 15
    datos_viejos: -15
    rol_expuesto: 50
    mfa_desactivada: 20
    contrasena_reutilizada: 25
    contrasenas_guardadas_en_navegador: 15
    redes_sociales_publicas: 15
    conexion_frecuente_a_redes_publicas: 10
    antivirus_desactivado: 15
    compras_online_frecuentes: 10
    backup_inexistente: 18


levels:
  25: Mínimo
  55: Bajo
  95: Medio
  130: Alto
  200: Crítico